### ISSUE TITLE
Problem with `console.log()` of RGBA images?

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#63] opened 2022-03-18 16:43 UTC
Is this what an RGBA image should look like when printed?
![image](https://user-images.githubusercontent.com/17711389/159045487-6758f3e2-99c1-4971-abd2-3d98362df56d.png)

Corresponding code: 
```ts
const image = testUtils.createRgbaImage([[255, 0, 0, 255, 0, 255, 0, 255]]);
console.log(image);
```

**Comment by targos** [comment] 2022-03-18 16:49
Duplicate of https://github.com/image-js/image-js-typescript/issues/31

**Closed by targos** 2022-03-18 16:49 UTC
Labels: bug
